name: ibank
description: "Your digital banking solution"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  double_tap_to_exit: ^1.0.2
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_local_notifications: ^19.4.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  local_auth: ^2.3.0
  pinput: ^5.0.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

  assets:
    - assets/images/
    - assets/icons/
