// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwkk9J-dlPt8irwTpTvI2k8KZ5SZ0GjqI',
    appId: '1:83879799411:android:b84078e2e1b4bbb00cd806',
    messagingSenderId: '83879799411',
    projectId: 'ibank-35e67',
    storageBucket: 'ibank-35e67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB8qqiAVTbBTlb9DvRMI-4jejcI9y3DPE',
    appId: '1:83879799411:ios:ff444910cd16c6a30cd806',
    messagingSenderId: '83879799411',
    projectId: 'ibank-35e67',
    storageBucket: 'ibank-35e67.firebasestorage.app',
    iosBundleId: 'com.omar.ibank',
  );
}
