name: Flutter iOS CI/CD Build IPA

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build (debug/release)'
        required: true
        default: 'release'
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'
      export_method:
        description: 'iOS export method (app-store, ad-hoc, development, enterprise)'
        required: true
        default: 'app-store'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build iOS IPA
      run: |
        flutter build ipa --${{ github.event.inputs.build_type }} \
          --export-method ${{ github.event.inputs.export_method }}

    - name: Archive built IPA
      uses: actions/upload-artifact@v4
      with:
        name: flutter-ios-${{ github.event.inputs.build_type }}-${{ github.event.inputs.export_method }}-ipa
        path: build/ios/archive/Runner.xcarchive/Products/Applications/*.ipa